# frozen_string_literal: true

require_relative 'error'

require_relative 'expression_fzs/shared'
require_relative 'expression_fzs/base'
require_relative 'expression_fzs/quantifier'
require_relative 'expression_fzs/subexpression'
require_relative 'expression_fzs/sequence'
require_relative 'expression_fzs/sequence_operation'

require_relative 'expression_fzs/classes/alternation'
require_relative 'expression_fzs/classes/anchor'
require_relative 'expression_fzs/classes/backreference'
require_relative 'expression_fzs/classes/character_set'
require_relative 'expression_fzs/classes/character_set/intersection'
require_relative 'expression_fzs/classes/character_set/range'
require_relative 'expression_fzs/classes/character_type'
require_relative 'expression_fzs/classes/conditional'
require_relative 'expression_fzs/classes/escape_sequence'
require_relative 'expression_fzs/classes/free_space'
require_relative 'expression_fzs/classes/group'
require_relative 'expression_fzs/classes/keep'
require_relative 'expression_fzs/classes/literal'
require_relative 'expression_fzs/classes/posix_class'
require_relative 'expression_fzs/classes/root'
require_relative 'expression_fzs/classes/unicode_property'

require_relative 'expression_fzs/methods/construct'
require_relative 'expression_fzs/methods/escape_sequence_char'
require_relative 'expression_fzs/methods/escape_sequence_codepoint'
require_relative 'expression_fzs/methods/human_name'
require_relative 'expression_fzs/methods/match'
require_relative 'expression_fzs/methods/match_length'
require_relative 'expression_fzs/methods/negative'
require_relative 'expression_fzs/methods/options'
require_relative 'expression_fzs/methods/parts'
require_relative 'expression_fzs/methods/printing'
require_relative 'expression_fzs/methods/referenced_expressions'
require_relative 'expression_fzs/methods/strfregexp'
require_relative 'expression_fzs/methods/tests'
require_relative 'expression_fzs/methods/traverse'
